"""add_category_to_messages_and_unanswered_queries

Revision ID: 57cd873d5e02
Revises: b3c943b424a7
Create Date: 2025-07-26 09:41:05.152721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cd873d5e02'
down_revision: Union[str, Sequence[str], None] = 'b3c943b424a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('unanswered_queries', sa.Column('category', sa.String(length=50), nullable=True))
    # Note: Removed alter_column for created_at as SQLite doesn't support it
    # op.create_foreign_key(None, 'unanswered_queries', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'unanswered_queries', type_='foreignkey')
    # Note: Removed alter_column for created_at as SQLite doesn't support it
    op.drop_column('unanswered_queries', 'category')
    op.drop_column('messages', 'category')
    # ### end Alembic commands ###
