"""add_user_question_to_messages

Revision ID: a15a9fdff269
Revises: 57cd873d5e02
Create Date: 2025-07-26 10:27:56.321206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15a9fdff269'
down_revision: Union[str, Sequence[str], None] = '57cd873d5e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_question', sa.Text(), nullable=True))
    # Note: Removed alter_column and create_foreign_key as SQLite doesn't support them
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed drop_constraint and alter_column as SQLite doesn't support them
    op.drop_column('messages', 'user_question')
    # ### end Alembic commands ###
