"""add reason+score to unanswered

Revision ID: c9636baac678
Revises: c2286ba5f52b
Create Date: 2025-07-18 11:04:44.305499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9636baac678'
down_revision: Union[str, Sequence[str], None] = 'c2286ba5f52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('unanswered_queries', sa.Column('reason', sa.String(), nullable=True))
    # op.add_column('unanswered_queries', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('ethnic_group', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('long_term_conditions', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('medications', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('consent_to_data_storage', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # op.alter_column('unanswered_queries', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unanswered_queries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('unanswered_queries', 'score')
    op.drop_column('unanswered_queries', 'reason')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'country')
    op.drop_column('users', 'address')
    op.drop_column('users', 'ethnic_group')
    op.drop_column('users', 'long_term_conditions')
    op.drop_column('users', 'medications')
    op.drop_column('users', 'consent_to_data_storage')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
